<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="1" disabled="0" errors="0" timestamp="2016-11-08T18:06:28" time="0.005" name="AllTests">
  <testsuite name="ExactSolutionPoissonHeatG26" tests="1" failures="1" disabled="0" errors="0" time="0.005">
    <testcase name="HandlesExactSolutionG26" status="run" time="0.005" classname="ExactSolutionPoissonHeatG26">
      <failure message="unknown file&#x0A;C++ exception with description &quot;&#x0A;--------------------------------------------------------&#x0A;An error occurred in line &lt;187&gt; of file &lt;/Users/neerajsarna/sciebo/DG_moments_deal/Tests/../include_new/Base_EquationGenerator.h&gt; in function&#x0A;    void EquationGenerator::Base_EquationGenerator&lt;2&gt;::build_triplet(std::vector&lt;triplet&gt; &amp;, const std::string) [dim = 2]&#x0A;The violated condition was: &#x0A;    in.is_open()&#x0A;The name and call sequence of the exception was:&#x0A;    ExcMessage(&quot;Triplet cant be read, file could not be opened&quot;)&#x0A;Additional Information: &#x0A;Triplet cant be read, file could not be opened&#x0A;--------------------------------------------------------&#x0A;&quot; thrown in the test body." type=""><![CDATA[unknown file
C++ exception with description "
--------------------------------------------------------
An error occurred in line <187> of file </Users/neerajsarna/sciebo/DG_moments_deal/Tests/../include_new/Base_EquationGenerator.h> in function
    void EquationGenerator::Base_EquationGenerator<2>::build_triplet(std::vector<triplet> &, const std::string) [dim = 2]
The violated condition was: 
    in.is_open()
The name and call sequence of the exception was:
    ExcMessage("Triplet cant be read, file could not be opened")
Additional Information: 
Triplet cant be read, file could not be opened
--------------------------------------------------------
" thrown in the test body.]]></failure>
    </testcase>
  </testsuite>
</testsuites>
