<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="4" failures="1" disabled="0" errors="0" timestamp="2017-02-06T17:34:10" time="283.304" name="AllTests">
  <testsuite name="LinearSolver" tests="1" failures="0" disabled="0" errors="0" time="0.042">
    <testcase name="HandlesLinearSolver" status="run" time="0.042" classname="LinearSolver" />
  </testsuite>
  <testsuite name="ResidualComputation" tests="1" failures="0" disabled="0" errors="0" time="0">
    <testcase name="HandlesResidualComputation" status="run" time="0" classname="ResidualComputation" />
  </testsuite>
  <testsuite name="ChecksPeriodicGrid" tests="1" failures="0" disabled="0" errors="0" time="0.211">
    <testcase name="HandlesPeridicGrid" status="run" time="0.21" classname="ChecksPeriodicGrid" />
  </testsuite>
  <testsuite name="SquareCavityG84" tests="1" failures="1" disabled="0" errors="0" time="283.051">
    <testcase name="SquareCavityG84" status="run" time="283.051" classname="SquareCavityG84">
      <failure message="unknown file&#x0A;C++ exception with description &quot;&#x0A;--------------------------------------------------------&#x0A;An error occurred in line &lt;194&gt; of file &lt;/home/sarna/Desktop/DG_moments_dealii/Tests/../include_new/Base_Solver.h&gt; in function&#x0A;    void FEM_Solver::Base_Solver&lt;dim&gt;::distribute_dof_allocate_matrix() [with int dim = 2]&#x0A;The violated condition was: &#x0A;    1==0&#x0A;Additional information: &#x0A;    Debugging&#x0A;--------------------------------------------------------&#x0A;&quot; thrown in the test body." type=""><![CDATA[unknown file
C++ exception with description "
--------------------------------------------------------
An error occurred in line <194> of file </home/sarna/Desktop/DG_moments_dealii/Tests/../include_new/Base_Solver.h> in function
    void FEM_Solver::Base_Solver<dim>::distribute_dof_allocate_matrix() [with int dim = 2]
The violated condition was: 
    1==0
Additional information: 
    Debugging
--------------------------------------------------------
" thrown in the test body.]]></failure>
    </testcase>
  </testsuite>
</testsuites>
